try:
    import asyncio
    from datetime import datetime
except Exception as e:
    print("Import Error: ", e)


class Logger(object):
    instance = None

    class __Logger:

        file_lock = asyncio.Lock()

        def __init__(self, output_file):
            self.logfile = output_file

    def __init__(self, output_file):
        if not Logger.instance:
            Logger.instance = Logger.__Logger(output_file)
        else:
            Logger.instance.logfile = output_file

    def save_log(self, log, error_msg=None):
        try:
            with open(self.instance.logfile, "a+") as file:
                now = datetime.now()
                current_time = now.strftime("%H:%M:%S")
                file.write(current_time+": ")
                file.write(str(log))
                file.write("\n")
            file.close()
            if error_msg is not None:
                self.save_log(error_msg)
        except Exception as e:
            print("Error while printing to logs file.")
            print(e)
